# Generated by Django 5.2 on 2025-04-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_store_store_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_zip_code_street',
            field=models.IntegerField(),
        ),
    ]
